### ISSUE TITLE
Err.The specified path are too long.MSB3491

### ISSUE THREAD

**Issue by hogaFarming** [BrowserSync/grunt-browser-sync#119]
I got an error when I install grunt-browser-sync.
It seems that **the specified path are too long** when installing this grunt plugin. 
Does it matter to running my Grunt project?Can anyone help? T-T

OS: Window 7
Operation: `npm install grunt-browser-sync --save-dev`

See this error:
```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

E:\learning>cd ..\l

E:\l>npm install grunt-browser-sync --save-dev
npm WARN optional dep failed, continuing fsevents@0.3.8
-
...
> utf-8-validate@1.1.0 install E:\l\node_modules\grunt-browser-sync\node_modules\browser-sync\node_m
odules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_mo
dules\utf-8-validate
> node-gyp rebuild


E:\l\node_modules\grunt-browser-sync\node_modules\browser-sync\node_modules\socket.io\node_modules\s
ocket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate>if not def
ined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\nod
e_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m"
switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(308,5): error MSB
3491: Could not write lines to file "Release\obj\validation\validation.tlog\validation.lastbuildsta
te". The specified path, file name, or both are too long. The fully qualified file name must be les
s than 260 characters, and the directory name must be less than 248 characters. [E:\l\node_modules\
grunt-browser-sync\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\n
ode_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1

gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\nod
e-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\
node-gyp.js" "rebuild"
gyp ERR! cwd E:\l\node_modules\grunt-browser-sync\node_modules\browser-sync\node_modules\socket.io\n
ode_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-valida
te
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
```

**Comment by shinnn** [comment]
https://github.com/BrowserSync/browser-sync/issues/734#issuecomment-123765529

**Comment by afennell** [comment]
Have tried something like npm ... --depth x ...
